const bills = [
  {
    "cf_ord_res_no_": " 312413",
    "committee": "Energy and Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jun 11,2012",
    "indexing_terms": " CITY-LIGHT,CITY-OFFICIALS-AND-AGENCIES",
    "record_type": "Clerk File ",
    "sponsor": " O'Brien",
    "title": " Reappointment and Oath of Office of Jorge Carrasco asSuperintendent of Seattle City Light, for a term of confirmation to July 23,2016.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312413&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 31394",
    "committee": "Libraries, Utilities, and Center",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jul 9,2012",
    "record_type": "Resolution ",
    "sponsor": " GODDEN",
    "title": " A RESOLUTION supporting the sale of certain water systemfacilities and transfer of a portion of retail water service to the City ofShoreline.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=31394&l=20&Sect5=RESNY&Sect6=HITOFF&d=RESF&p=1&u=%2F~public%2FRESNy.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117523",
    "committee": "Public Safety, Civil Rights, and Technology",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jul 16,2012",
    "record_type": "Council Bill ",
    "sponsor": " HARRELL",
    "title": " AN ORDINANCE relating to the Technology Matching Fund Program;making allocations and authorizing implementation of certain TechnologyMatching Fund projects in 2012; providing that 2012 appropriations for theTechnology Matching Fund from the Cable Television Franchise Subfund and fromthe Information Technology Fund shall automatically carry forward into the 2013fiscal year; that any unspent funds from an individual project may be appliedto another Technology Matching Fund project; and ratifying and confirmingcertain prior acts.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117523&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312357",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " May 21,2012",
    "indexing_terms": " CONTRACT-REZONES, MIXED-USE-DEVELOPMENT, NORTHGATE,MAPLE-LEAF",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Application of Wallace GT-Northgate II LLC, for a contractrezone of 72,985 square feet of land at 525 NE Northgate Way from NeighborhoodCommercial 3 with a 65 foot height limit (NC3-65) to Neighborhood Commercial 3with an 85 foot height limit (NC3-85) for future construction of a seven-storystructure containing 22,976 square feet of commercial space, 262 residentialunits, and below-grade parking for 270 vehicles (Project No. 3012842, TypeIV.)",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312357&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312319",
    "committee": "Transportation",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " May 7,2012",
    "indexing_terms": " VACATING, LOWER-QUEEN-ANNE, CASCADE,SOUTH-LAKE-UNION",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Application of IRIS Holdings, LLC, to vacate a portion of BroadStreet between Harrison Street and Sixth Avenue North as initiated byResolution 31374.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312319&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312333",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " May 7,2012",
    "record_type": "Clerk File ",
    "sponsor": " Conlin",
    "title": " Reappointment of David M. Namura as member, Seattle ChinatownInternational District Preservation and Development Authority Council, for aterm of confirmation to December 31, 2015.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312333&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312300",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Apr 30,2012",
    "record_type": "Clerk File ",
    "sponsor": " NoSponsor Required",
    "title": " Application of Greystar Real Estate Partners, LLC, for a rezoneof approximately 43,200 square feet of land at 400 Boren Avenue North fromIndustrial Commercial with a 65 foot height limit (IC-65) to Seattle Mixed withan 85 foot height limit (SM-85), to construct a seven-story residentialbuilding and below grade parking (Project No. 3013013, Type IV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312300&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312299",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Apr 30,2012",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Council Conditional Use application of King County Department ofNatural Resources and Parks, Wastewater Treatment Division, to expand anexisting stormwater treatment facility (North Beach Combined Sewer Overflow),located at 9921 Triton Drive Northwest, to include a new 325 foot long buriedstorage pipe within the Triton Drive right of way and a new 1,900 square footabove ground mechanical structure on the existing treatment facility site(Project No. 3012914, Type IV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312299&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312266",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Apr 9,2012",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Council land use action to allow poles and netting up to 140feet in height for a new driving range at Jackson Park Golf Course, located at1000 NE 135th Street (Project No. 3012923, Type V).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312266&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312262",
    "committee": "Transportation",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Apr 9,2012",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Petition for Amazon.com, Inc., to vacate the alley in Block 20,Heirs of Sarah A. Bell's Second Addition to Seattle.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312262&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312261",
    "committee": "Transportation",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Apr 9,2012",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Petition for Amazon.com, Inc., to vacate the alley in Block 19,Heirs of Sarah A. Bell's Second Addition to Seattle.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312261&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312260",
    "committee": "Transportation",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Apr 9,2012",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Petition for Amazon.com, Inc., to vacate the alley in Block 14,Heirs of Sarah A. Bell's Addition to Seattle.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312260&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312251",
    "committee": "Transportation",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Apr 2,2012",
    "record_type": "Clerk File ",
    "sponsor": "Rasmussen",
    "title": " Reappointment of Mark Landreneau as member, Seattle PedestrianAdvisory Board, for a term of confirmation to March 4, 2014.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312251&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312238",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Mar 26,2012",
    "record_type": "Clerk File ",
    "sponsor": "Conlin",
    "title": " Appointment of Morgan Shook as member, Seattle PlanningCommission, for a term of confirmation to April 15, 2014.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312238&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312229",
    "committee": "Public Safety, Civil Rights, and Technology",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Mar 26,2012",
    "record_type": "Clerk File ",
    "sponsor": "Harrell",
    "title": " Reappointment of Philip Dovinh as member, Seattle Fire CodeAdvisory Board, for a term of confirmation to March 30, 2015.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312229&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312119",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Feb 13,2012",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Council land use action to allow a new 19,800 square foottwo-story clubhouse and driving range structure, a new 4,100 square foot cartstorage structure and 20,000 square feet of paving improvements, including arequest to waive development standards to allow field lighting up to 90 feet inheight and netting and net poles up to 140 feet in height (Project No 3012845,Type V).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312119&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312105",
    "committee": "Economic Resiliency and Regional Relations",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 30,2012",
    "record_type": "Clerk File ",
    "sponsor": " Clark",
    "title": " Reappointment of Rico Quirindongo as member, Historic SeattlePreservation Development Authority Council, for a term of confirmation toDecember 1, 2013.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312105&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312104",
    "committee": "Economic Resiliency and Regional Relations",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 30,2012",
    "record_type": "Clerk File ",
    "sponsor": " Clark",
    "title": " Reappointment of Alex Rolluda as member, Pike Place MarketHistorical Commission, for a term of confirmation to December 1,2013.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312104&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312089",
    "committee": "Parks and Neighborhoods",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 30,2012",
    "record_type": "Clerk File ",
    "sponsor": "Bagshaw",
    "title": " Appointment of Barbara A. Wright as member, Seattle Board ofPark Commissioners, for a term of confirmation to March 31, 2015.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312089&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312087",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 30,2012",
    "record_type": "Clerk File ",
    "sponsor": " Nosponsor required",
    "title": " Council land use action to allow an expansion to an existingpublic facility (Pump Station #39) in an environmentally critical area locatedat 5080 Beach Drive Southwest (Project No. 3012748, Type V).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312087&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312040",
    "committee": "Public Safety, Civil Rights, and Technology",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 17,2012",
    "record_type": "Clerk File ",
    "sponsor": "Harrell",
    "title": " Reappointment of Rose Hickman as member, Seattle Women'sCommission, for a term of confirmation to July 1, 2013.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312040&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312006",
    "committee": "Public Safety, Civil Rights, and Technology",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 17,2012",
    "record_type": "Clerk File ",
    "sponsor": "Harrell",
    "title": " Appointment of Emily L. Alvarado as member, Seattle Women'sCommission, for a term of confirmation to July 1, 2012.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312006&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 312005",
    "committee": "Public Safety, Civil Rights, and Technology",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 17,2012",
    "record_type": "Clerk File ",
    "sponsor": "Harrell",
    "title": " Appointment of Levonne Abshire as member, Seattle Women'sCommission, for a term of confirmation to July 1, 2012.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=312005&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 311973",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 9,2012",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Application of Murphy McCullough for a contract rezone ofapproximately 40,000 square feet of land at 3400 Stone Way North fromIndustrial Commercial with a 45 foot height limit (IC 45) to IndustrialCommercial with a 65 foot height limit (IC 65) (Project No. 3012601, TypeIV.)",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=311973&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 311936",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 17,2012",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Application of Swedish Health Services to prepare a new MajorInstitution Master Plan for the Swedish Hospital Cherry Hill Campus, located at500 17th Avenue (DPD Project No. 3012953, Type IV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=311936&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 311931",
    "committee": "Housing, Human Services, Health, and Culture",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Dec 12,2011",
    "record_type": "Clerk File ",
    "sponsor": "Licata",
    "title": " Appointment of Christina Orr-Cahall as member, Seattle MusicCommission, for a term of confirmation to May 1, 2014.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=311931&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 311916",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 9,2012",
    "misc_notes": "Originally referred to Committee on the Built Environment on December 12,2011.",
    "record_type": "Clerk File ",
    "sponsor": "Conlin",
    "title": " Reappointment of Kevin D. McDonald as member, Seattle PlanningCommission, for a term of confirmation to April 15, 2014.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=311916&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 311901",
    "committee": "Public Safety, Civil Rights, and Education",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 17,2012",
    "misc_notes": " Originally referred to the Energy, Technology,and Civil Rights Committee on December 5, 2011.",
    "record_type": "Clerk File ",
    "sponsor": "Harrell",
    "title": " Appointment of Shaunita Felder as member, Seattle LGBTCommission, for a term of confirmation to April 30, 2012.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=311901&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 311874",
    "committee": "Transportation",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Nov 14,2011",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Petition of Fred Hutchinson Cancer Research Center to theSeattle City Council for a skybridge permit pursuant to Seattle Municipal Code15.64, for a new skybridge connecting 1100 Eastlake Ave E with the FredHutchinson Cancer Research Center campus.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=311874&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 311872",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Apr 16,2012",
    "misc_notes": " Originally referred to Committee on theBuilt Environment on November 7, 2011.",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Council Conditional Use application of King County to allow a5,600 square foot expansion to a public facility, including 2,600 cubic yardsof grading, in an environmentally critical area at the West Point TreatmentPlant, located at 4215 36th Avenue West (Project No. 3012604, TypeIV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=311872&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 311813",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Apr 16,2012",
    "misc_notes": " Originally referred to Committee on theBuilt Environment on October 3, 2011.",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Application of R.C. Backer for a contract rezone ofapproximately 12,800 square feet of land at 225 West Galer Street fromNeighborhood Commercial 2 with a 30 foot limit (NC3-30') to NeighborhoodCommercial 2 with a 40 foot limit in height (NC2- 40'), to construct a 27,000square foot, three-story 48 unit assisted living facility, to include 18parking stalls in a 21,000 sq. ft. of below grade area. (Project No. 3012582,Type IV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=311813&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 311812",
    "committee": "Built Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Oct 3,2011",
    "record_type": "Clerk File ",
    "sponsor": " Clark",
    "title": " Application of Trenton Associates-McClellan LLC for approval ofa contract rezone of approximately 67,948 sq. ft. of land at 2615 25th AvenueSouth from Single Family 5000 (SF 5000) to Seattle Mixed with a 65 foot limit(SM - 65'), to allow a seven story structure containing 198 residential unitswith parking for 148 vehicles, and including 13, 230 cu. yds. of grading in anenvironmentally critical area.  (Related Project No. 3012417; Project No.3012217, Type IV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=311812&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 311694",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Apr 16,2012",
    "misc_notes": "Originally referred to Committee on the Built Environment on August 15,2011.",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Application of Gregory N. Nalbandian on behalf of John W. Lashfor approval of a contract rezone of land at 10001 Lake City Way NE from SingleFamily 5000 (SF 5000) to Commercial 1 (C1-40), for future construction of an800 sq. ft. accessory structure to an existing warehouse in an environmentallycritical area (Project No. 3012420, Type IV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=311694&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 311685",
    "committee": "Transportation",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Aug 8,2011",
    "indexing_terms": " VACATING, CASCADE,EASTLAKE",
    "record_type": "Clerk File ",
    "sponsor": "Rasmussen",
    "title": " Petition of Alexandria Real Estate Equities, Inc. for thevacation of East Nelson Place at 1150 Eastlake Avenue East.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=311685&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 311623",
    "committee": "Built Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jun 27,2011",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Application by Scott Roberts for a contract rezone of land at2615 25th Avenue South from Single Family 5000 (SF 5000) to NeighborhoodCommercial 3 (NC 3) with a 65 foot limit for future construction of six-storymultifamily residential structures with accessory parking. (DPD Project Numbers312217 and 3012417, Type IV)",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=311623&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 311541",
    "committee": "Built Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " May 23,2011",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Application of Clayton Graham to rezone approximately 109,571square feet of land at 307 Fairview Avenue North and 334 Boren Avenue North,from Industrial Commercial with a 65 foot height limit (IC-65) to Seattle Mixedwith a 65 foot height limit (SM-65), and approximately 110,442 square feet ofland at 1120 John Street from Industrial Commercial with an 85 foot heightlimit (IC-85) to Seattle Mixed with an 85 foot height limit (SM-85) (ProjectNo. 3012117, Type IV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=311541&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 311533",
    "committee": "Housing, Human Services, Health, and Culture",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " May 16,2011",
    "record_type": "Clerk File ",
    "sponsor": "Licata",
    "title": " Appointment of Gian-Carlo Scandiuzzi as member, Seattle ArtsCommission, for a term of confirmation to December 31, 2012.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=311533&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 311240",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Apr 16,2012",
    "indexing_terms": " REZONES",
    "misc_notes": " Originally referred to Committeeon the Built Environment on January 3, 2011.",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Application of Northgate Plaza L.L.C and T&M Jenn L.P. to rezone365,040 sq.  ft. of land at 11200 1st Avenue Northeast from Midrise (MR) toNeighborhood Commercial 3 with an 85 foot height limit (NC3 85) (Project No.3006101, Type IV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=311240&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 311081",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Apr 16,2012",
    "misc_notes": " Originally referredto the Committee on the Built Environment on October 11, 2010.",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Application of Katy Chaney to prepare a new Major InstitutionMaster Plan for the Virginia Mason Medical Center campus, located at 1100 9thAvenue (Project No. 3011669, Type IV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=311081&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 310934",
    "committee": "Housing, Human Services, Health, and Culture",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jul 12,2010",
    "record_type": "Clerk File ",
    "sponsor": " Licata",
    "title": " Appointment of Michael Kerns as member, Capitol Hill HousingImprovement Program Council, for a term of confirmation to April 30,2013.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=310934&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 310853",
    "committee": "Built Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jun 14,2010",
    "record_type": "Clerk File ",
    "sponsor": "Clark",
    "title": " Application of Edward Hewson to rezone 203,857 square feet ofland at 6501 15th Avenue NE (Project #3010100, Type IV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=310853&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 310087",
    "committee": "Built Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 19,2010",
    "indexing_terms": " LAND-USE-PERMITS, SEATTLE-PUBLIC-UTILITIES,FLOOD-CONTROL-AND-DRAINAGE, STORM-SEWERS",
    "misc_notes": " Originally referred toPlanning, Land Use, and Neighborhoods Committee on 7/13/09.",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Council Concept Approval to allow a new utility service use(Seattle Public Utilities stormwater facility) located at 2300 Arboretum DriveEast (Project No. 3010263, Type V)",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=310087&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 310077",
    "committee": "Built Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 19,2010",
    "indexing_terms": " REZONES, GREENWOOD",
    "misc_notes": "Fred Meyer RezoneOriginally referred to Planning, Land Use, and Neighborhoods Committee on7/13/09.",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Petition of Chris Libby to rezone land at 100 NW 85th Streetfrom Commercial 1 with a 40 foot height limit (C1-40) to Commercial 1 with a 65foot height limit (C1-65) (Project No. 3010265, Type IV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=310077&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 309618",
    "committee": "Built Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 19,2010",
    "indexing_terms": " REZONES, WEST-SEATTLE",
    "misc_notes": "Originally referred to Planning, Land Use, and Neighborhoods Committee on10/20/08.",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Application of The Kenney for a contract rezone of 73,459 squarefeet of land at 7125 Fauntleroy Way Southwest, from Lowrise Duplex/Triplex(LDT) to Lowrise 3 (L3) (Project No. 3008453/Type IV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=309618&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 309531",
    "committee": "Built Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 19,2010",
    "indexing_terms": " REZONES, OLYMPIC-HILLS",
    "misc_notes": " Originally referred toPlanning, Land Use, and Neighborhoods Committee on 8/18/08.",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Application of Lorig Associates for a contract rezone of 117,000square feet of land at 2611 Northeast 125th Street from Lowrise 2 (L2) andLowrise 3 (L3) multifamily residential to Midrise (MR) multifamily residential(Project No. 3008858/Type IV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=309531&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 309530",
    "committee": "Built Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 19,2010",
    "indexing_terms": " INTERBAY, REZONES",
    "misc_notes": " Originally referred toPlanning, Land Use, and Neighborhoods Committee on 8/18/08.",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Application of Nitty Gritty L.L.C. for a contract rezone of50,844 square feet of land at 1616 West Bertona Street from General Industrial1 with a 45 foot height limit for most non-industrial uses (IG/U 45) toIndustrial Commercial with a 45 foot height limit (IC 45) (Project No.3009004/Type IV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=309530&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 309497",
    "committee": "Built Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 19,2010",
    "indexing_terms": " REZONES, MAGNOLIA",
    "misc_notes": "Originally referred to Planning, Land Use, and Neighborhoods Committee on7/21/08.",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Petition of Keith Hammer and Blair Stone to rezone 21,386 sq.ft.of land at 2200 32nd Av. W. from Single Family 5000 (SF 5000) to Lowrise 1 (L1)multifamily residential (Project No. 3005123/Type IV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=309497&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 309092",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Apr 23,2012",
    "indexing_terms": " QUASI-JUDICIAL-REZONES,SEATTLE-UNIVERSITY",
    "misc_notes": " Originally referred to Planning, Land Use, andNeighborhoods on 5/18/09. Re-referred to Committee on the Built Environment on1/19/10.",
    "record_type": "Clerk File ",
    "sponsor": " No Sponsor Required",
    "title": " Application of Seattle University to prepare a new majorinstitution master plan for the Seattle University Campus, located at 901 12thAvenue (Project No. 3008328, Type IV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=309092&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 307575",
    "committee": "Built Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jun 14,2010",
    "indexing_terms": " REZONES, CROWN-HILL, BALLARD",
    "misc_notes": " Originallyreferred to Urban Development & Planning on 8/15/05.",
    "record_type": "Clerk File ",
    "sponsor": " Clark",
    "title": " Petition of Remedios and Jesus Eballar to rezone a portion of a5,349 square foot parcel of land located at 9030 - 13th Avenue NW, from SF 5000to C-1 40' (Project No. 3001440 - Type IV).",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=307575&l=20&Sect5=CFCF1&Sect6=HITOFF&d=CFCF&p=1&u=%2F~public%2FCFCF1.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 31393",
    "committee": "Transportation",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jul 2,2012",
    "indexing_terms": " AUDITS, PROGRAM-EVALUATION,TRANSPORTATION-DEPARTMENT",
    "record_type": "Resolution ",
    "sponsor": "RASMUSSEN",
    "title": " A RESOLUTION establishing goals and objectives for anoperational efficiencies review of the Seattle Department ofTransportation andcreating a joint City Council, Executive and Office of the City Auditorinterdepartmental team to oversee project implementation.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=31393&l=20&Sect5=RESNY&Sect6=HITOFF&d=RESF&p=1&u=%2F~public%2FRESNy.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 31381",
    "committee": "Transportation",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " May 14,2012",
    "indexing_terms": " FRANCHISES, PIPELINES, PERMITS,DOWNTOWN, RAINIER-VALLEY, INDUSTRIAL-DISTRICT, STREETS, ALLEYS,FEES",
    "record_type": "Resolution ",
    "sponsor": "RASMUSSEN",
    "title": " A RESOLUTION relating to the franchise permit granted to theSeattle Steam Limited Partnership by Ordinance 121067, as amended by Ordinance122260, to maintain and operate a thermal energy system in and along certainstreets, avenues, alleys, and public places in the City of Seattle byestablishing the annual fee for the next ten years of the permit.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=31381&l=20&Sect5=RESNY&Sect6=HITOFF&d=RESF&p=1&u=%2F~public%2FRESNy.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 31353",
    "committee": "Energy and Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 17,2012",
    "indexing_terms": " ENVIRONMENTAL-CLEANUP, CITY-LIGHT,DUWAMISH-WATERWAY",
    "record_type": "Resolution ",
    "sponsor": " O'BRIEN",
    "title": " A RESOLUTION relating to the City Light Department; authorizingthe deferral of certain environmental costs for cleanup of designated Superfundsites in accordance with Accounting Standards Codifications (ASC) 980-340-25- 1Regulated Operations-Other Assets and Deferred Costs- Recognition 5-25-25-1 andsubsequent amendments.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=31353&l=20&Sect5=RESNY&Sect6=HITOFF&d=RESF&p=1&u=%2F~public%2FRESNy.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117376",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jan 9,2012",
    "misc_notes": " Originally referred to Committee onthe Built Environment on December 12, 2011.",
    "record_type": "Council Bill ",
    "sponsor": " CONLIN",
    "title": " AN ORDINANCE relating to land use and zoning, amending theOfficial Land Use Map at pages 159, 173, and 174 to rezone land in the MLK atHolly St Residential Urban Village.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117376&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117520",
    "committee": "Libraries, Utilities, and Center",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jul 16,2012",
    "indexing_terms": " UTILITY-RATES, DRAINAGE,DRAINAGE-AND-WASTEWATER-UTILITY, LOW-INCOME, WASTE-WATER-TREATMENT,PUBLIC-ASSISTANCE",
    "record_type": "Council Bill ",
    "sponsor": " GODDEN",
    "title": " AN ORDINANCE relating to drainage services of Seattle PublicUtilities (SPU); amending Section 21.33.010 of the Seattle Municipal Code toupdate definitions; amending Section 21.33.030 of the Seattle Municipal Code toupdate exemptions from drainage rates and adjust drainage rates; amendingSections 21.33.050 and 21.33.070 to clarify billing and collection procedures;and amending Section 21.76.040 of the Seattle Municipal Code to revise creditsto low-income drainage customers.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117520&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117522",
    "committee": "Libraries, Utilities, and Center",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jul 16,2012",
    "indexing_terms": " SEATTLE-PUBLIC-UTILITIES, UTILITY-RATES,SOLID-WASTE, SOLID-WASTE-DISPOSAL, LOW-INCOME,PUBLIC-ASSISTANCE",
    "record_type": "Council Bill ",
    "sponsor": " GODDEN",
    "title": " AN ORDINANCE relating to the solid waste system of SeattlePublic Utilities; revising rates and charges for solid waste services; revisingcredits to low income customers for solid waste services; offering freedisposal at City recycling and disposal stations to low income customers undercertain conditions; revising rates for yellow pages phone book recovery fees;providing for an annual adjustment to rates and charges for inflationaryadjustments to contractor payments; and amending Chapters 21.40, 21.76 and6.255 of the Seattle Municipal Code.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117522&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117521",
    "committee": "Libraries, Utilities, and Center",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jul 16,2012",
    "indexing_terms": " UTILITY-RATES,DRAINAGE, DRAINAGE-AND-WASTEWATER-UTILITY, LOW-INCOME,WASTE-WATER-TREATMENT",
    "record_type": "Council Bill ",
    "sponsor": "GODDEN",
    "title": " AN ORDINANCE relating to wastewater services of Seattle PublicUtilities; amending Section 21.28.040 of the Seattle Municipal Code to adjustthe wastewater volume rate; and amending Subsection 21.76.040 A of the SeattleMunicipal Code to adjust credits to low-income wastewater customers.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117521&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117518",
    "committee": "Transportation",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jul 9,2012",
    "indexing_terms": " PARKING,PARKING-METERS, COMPREHENSIVE-PLAN, URBAN-AREAS,",
    "record_type": "Council Bill ",
    "sponsor": " RASMUSSEN",
    "title": " AN ORDINANCE relating to parking time-limits on Sundays;amending Seattle Municipal Code section 11.76.020 to allow time-limitedparking, as indicated by signposting, on Sundays in paid parkingareas.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117518&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117515",
    "committee": "Libraries, Utilities, and Center",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jul 9,2012",
    "indexing_terms": "TELECOMMUNICATIONS",
    "record_type": "Council Bill ",
    "sponsor": " GODDEN",
    "title": " AN ORDINANCE relating to the Seattle Center Department;authorizing execution of a right of entry agreement with Comcast CableCommunications Management, LLC and a license agreement with KCTS Television, toallow for access of conduit and installation of fiber optic cable and relatedequipment needed to provide various communication services at SeattleCenter.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117515&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117516",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jul 9,2012",
    "indexing_terms": " ENERGY-CONSERVATION, GREEN-BUILDING,ENVIRONMENTAL-HEALTH, ENVIRONMENTAL-PROTECTION, LAND-USE-CODE, CONSTRUCTION,BUILDING-METHODS",
    "record_type": "Council Bill ",
    "sponsor": " CONLIN",
    "title": " AN ORDINANCE relating to land use and zoning, amending Sections23.40.060 and 23.41.012 of the Seattle Municipal Code to provide additionaldesign departures under the Demonstration Program for Living Building Designimplemented by Section 23.40.060.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117516&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117430",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Mar 26,2012",
    "indexing_terms": " LAND-USE-PERMITS, LAND-USE-REGULATIONS,ACCESSORY-HOUSING, SINGLE-FAMILY-RESIDENTIAL-AREAS,MULTI-FAMILY-RESIDENTIAL-AREAS, ZONING, LAND-USE-REGULATIONS, SCHOOLS,HOSPITALS, PARKING",
    "record_type": "Council Bill ",
    "sponsor": " CONLIN",
    "title": " AN ORDINANCE related to land use, zoning and environmentalreview, amending Sections 23.40.006, 23.42.040, 23.42.050, 23.44.014,23.44.041, 23.45.504, 23.45.510, 23.45.512, 23.45.514, 23.45.518, 23.45.526,23.45.527, 23.45.529, 23.45.532, 23.45.545, 23.47A.005, 23.47A.008, 23.54.015,23.54.016, 23.54.020, 23.55.022, 23.76.004, 23.76.006, 23.84A.032, 23.91.002,25.05.800 and Chapter 23.52 of the Seattle Municipal Code, and adding newSections 23.40.035 and 23.52.008 to carry out proposals for regulatoryreform.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117430&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117513",
    "committee": "Public Safety, Civil Rights, and Technology",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jul 2,2012",
    "indexing_terms": "CRIMINAL-OFFENSES, LAW-ENFORCEMENT, VICTIMS-AND-WITNESSES, PROSTITUTION, FEES,FINES, CRIMINAL-LAW, CRIME-PREVENTION,CORRECTIONAL-PUNISHMENT-AND-REHABILITATION",
    "record_type": "Council Bill ",
    "sponsor": "HARRELL",
    "title": " AN ORDINANCE relating to the City's criminal code; amending andadding various sections and subsections in Chapters 12A.06 and 12A.10 of theSeattle Municipal Code to conform with changes in state law.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117513&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117512",
    "committee": " Public Safety, Civil Rights, and Technology",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jul 2,2012",
    "indexing_terms": " TRAFFIC, DRUG-RELATED-CRIMES, VEHICLE-REGISTRATION,DRUG-ENFORCEMENT, LICENSES, MOTOR-VEHICLES, MUNICIPAL-COURT, MOTOR-VEHICLES,ALCOHOLIC-BEVERAGE-CONTROL, ALCOHOLIC-BEVERAGE-CONTROL, CRIMINAL-OFFENSES,ALCOHOLIC-BEVERAGE-CONTROL, LAW-ENFORCEMENT",
    "record_type": "Council Bill ",
    "sponsor": " HARRELL",
    "title": " AN ORDINANCE relating to the City's traffic code; amendingvarious sections and subsections in Chapters 11.14, 11.22, 11.31, 11.32, 11.54,11.56, 11.58, 11.59 and 11.84 of the Seattle Municipal Code to conform withchanges in state law.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117512&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117511",
    "committee": "Transportation",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jul 2,2012",
    "indexing_terms": " CONSTRUCTION,METRO, QUEEN-ANNE, LAND-USE-PERMITS, INTERLOCAL-AGREEMENTS, SUBSTATIONS,MASS-TRANSIT, LAND-USE-REGULATIONS",
    "record_type": "Council Bill ",
    "sponsor": " RASMUSSEN",
    "title": " AN ORDINANCE granting King County permission to maintain andoperate a D-C Substation in connection with its publicTransportation system,on Valley Street, east of 1st Avenue North, for an unlimited term; specifyingthe conditions under which this permit is granted; providing for the acceptanceof the permit and conditions; and ratifying and confirming certain prioracts.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117511&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117510",
    "committee": "Transportation",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jul 2,2012",
    "indexing_terms": " PERMITS, STREET-USE-PERMITS, OVERPASSES,FREMONT",
    "record_type": "Council Bill ",
    "sponsor": " RASMUSSEN",
    "title": " AN ORDINANCE, relating to the permission granted to the QuadrantCorporation by Ordinance 118908, as amended by Ordinances 121855 and 123801, toconstruct, maintain, and operate a vehicular and pedestrian ramp over NorthNorthlake Way beneath the George Washington Memorial (Aurora Avenue) Bridge, byamending Section 1 to revise the legal description of the adjacent property;and ratifying and confirming certain prior acts.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117510&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117509",
    "committee": "Transportation",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jul 2,2012",
    "indexing_terms": "TRAFFIC, PARKING, FEES, TELECOMMUNICATIONS, PARKING-METERS",
    "record_type": "Council Bill ",
    "sponsor": " RASMUSSEN",
    "title": " AN ORDINANCE relating to the Traffic Code; allowing payment forparking in City public rights-of-way by mobile device; authorizing the DirectorofTransportation to enter into contracts and to set convenience fees to becharged for pay by mobile device services; amending Sections 11.14.425,11.76.005, 11.76.010 and 11.76.015 of the Seattle Municipal Code; and adding anew Section 11.16.127.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117509&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117508",
    "committee": "Libraries, Utilities, and Center",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jul 2,2012",
    "indexing_terms": "RECREATIONAL-FACILITIES, TRAILS, TOLT-RIVER, LAKE-YOUNGS, RATTLESNAKE-LAKE,INTERLOCAL-AGREEMENTS, CEDAR-RIVER, RIGHT-OF-WAY,",
    "record_type": "Council Bill ",
    "sponsor": " GODDEN",
    "title": " AN ORDINANCE relating to a recreational trails agreement withKing County; authorizing the Director of Seattle Public Utilities to grant KingCounty permission to develop and operate recreational trails on portions ofutility property in the Tolt Right of Way, the Lake Youngs Reservoir area, theWest Seattle Right of Way, the Snoqualmie Valley/Rattlesnake Lake area, and theCedar River Pipeline Drain Right of Way; in partial consideration for which theCounty will grant the City permission to use King County property in thevicinity of Rattlesnake Lake for recreational trails and an access road; andauthorizing the Director to execute the agreement for these propertyuses.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117508&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117506",
    "committee": "Planning, Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jun 25,2012",
    "indexing_terms": " GREENWOOD, PHINNEY-RIDGE, LAND-USE-CODE, ZONING,LOW-INCOME-HOUSING, MODERATE-INCOME-HOUSING,",
    "record_type": "Council Bill ",
    "sponsor": " CONLIN",
    "title": " AN ORDINANCE related to land use and zoning; amending page 25 ofthe Official Land Use Map, Seattle Municipal Code Chapter 23.32, to rezoneproperties located in the Greenwood/Phinney Ridge Residential Urban Village andapplying incentive provisions for affordable housing within the rezonearea.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117506&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117505",
    "committee": "Energy and Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jun 25,2012",
    "indexing_terms": "ENERGY-RESOURCES, ENERGY-FACILITIES, CONTRACTS, WIND-ENERGY",
    "record_type": "Council Bill ",
    "sponsor": " O'BRIEN",
    "title": " AN ORDINANCE relating to the City Light Department; authorizingexecution of a 20-year agreement with WM Renewable Energy, LLC for the purchaseof renewable power and environmental attributes from the expansion of theColumbia Ridge landfill gas generating facility that are necessary orconvenient for reliably meeting load growth and meeting the requirements of theWashington State Energy Independence Act; and further authorizing the executionof other necessary and convenient agreements for the receipt, tracking,transmitting, transferring, management and sale of power and environmentalattributes from the Columbia Ridge landfill gas generating facilityexpansion.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117505&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117504",
    "committee": "Energy and Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jun 25,2012",
    "indexing_terms": " HYDROELECTRIC-FACILITIES, DAMS, BOUNDARY-PROJECT,US-GOVERNMENT",
    "record_type": "Council Bill ",
    "sponsor": " O'BRIEN",
    "title": " AN ORDINANCE relating to the City Light Department andauthorizing the Superintendent of the City Light Department to accept on behalfof the City the new license from the Federal Energy Regulatory Commission tooperate Seattle's Boundary Dam Hydroelectric Project (FERC Project No. 2144);and ratifying and confirming prior acts.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117504&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117497",
    "committee": "Transportation",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jun 18,2012",
    "indexing_terms": "REGIONAL-TRANSIT-AUTHORITY, CONSTRUCTION, STREETCARS, MASS-TRANSIT, FIRST-HILL,BROADWAY, BUDGET,",
    "record_type": "Council Bill ",
    "sponsor": " RASMUSSEN",
    "title": " AN ORDINANCE relating to the Transit Corridor Projects project;removing restrictions in the 2012 Adopted Budget that limit the SeattleDepartment ofTransportation's spending in the Mobility-Capital BCL; andrevising project allocations in the 2012-2017 Capital ImprovementProgram.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117497&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117495",
    "committee": "Energy and Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jun 11,2012",
    "indexing_terms": "ENERGY-RESOURCES, ENERGY-FACILITIES, CONTRACTS, WIND-ENERGY",
    "record_type": "Council Bill ",
    "sponsor": " O'BRIEN",
    "title": " AN ORDINANCE relating to the City Light Department; authorizingthe execution of a confirmation agreement with Salmon Falls Wind Park, LLC forthe purchase of environmental attributes, which include renewable energycertificates that are necessary or convenient for meeting the requirements ofthe Washington State Energy Independence Act; and further authorizing theexecution of other necessary and convenient agreements for the receipt,tracking, transferring, management, and sale of the environmentalattributes.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117495&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117494",
    "committee": "Energy and Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jun 11,2012",
    "indexing_terms": "ENERGY-RESOURCES, ENERGY-FACILITIES, CONTRACTS, WIND-ENERGY",
    "record_type": "Council Bill ",
    "sponsor": " O'BRIEN",
    "title": " AN ORDINANCE relating to the City Light Department; authorizingthe execution of a confirmation agreement with Tuana Gulch Wind Park, LLC forthe purchase of environmental attributes, which include renewable energycertificates that are necessary or convenient for meeting the requirements ofthe Washington State Energy Independence Act; and further authorizing theexecution of other necessary and convenient agreements for the receipt,tracking, transferring, management, and sale of the environmentalattributes.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117494&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117493",
    "committee": "Energy and Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jun 11,2012",
    "indexing_terms": "ENERGY-RESOURCES, ENERGY-FACILITIES, CONTRACTS, WIND-ENERGY",
    "record_type": "Council Bill ",
    "sponsor": " O'BRIEN",
    "title": " AN ORDINANCE relating to the City Light Department; authorizingthe execution of a confirmation agreement with Golden Valley Wind Park, LLC forthe purchase of environmental attributes, which include renewable energycertificates that are necessary or convenient for meeting the requirements ofthe Washington State Energy Independence Act; and further authorizing theexecution of other necessary and convenient agreements for the receipt,tracking, transferring, management, and sale of the environmentalattributes.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117493&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117492",
    "committee": "Energy and Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jun 11,2012",
    "indexing_terms": "ENERGY-RESOURCES, ENERGY-FACILITIES, CONTRACTS, WIND-ENERGY",
    "record_type": "Council Bill ",
    "sponsor": " O'BRIEN",
    "title": " AN ORDINANCE relating to the City Light Department; authorizingthe execution of a confirmation agreement with the Oregon Trail Wind Park, LLCfor the purchase of environmental attributes, which include renewable energycertificates that are necessary or convenient for meeting the requirements ofthe Washington State Energy Independence Act; and further authorizing theexecution of other necessary and convenient agreements for the receipt,tracking, transferring, management, and sale of the environmentalattributes.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117492&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117491",
    "committee": "Energy and Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jun 11,2012",
    "indexing_terms": "ENERGY-RESOURCES, ENERGY-FACILITIES, CONTRACTS, WIND-ENERGY",
    "record_type": "Council Bill ",
    "sponsor": " O'BRIEN",
    "title": " AN ORDINANCE relating to the City Light Department; authorizingthe execution of a confirmation agreement with Thousand Springs Wind Park, LLCfor the purchase of environmental attributes, which include renewable energycertificates that are necessary or convenient for meeting the requirements ofthe Washington State Energy Independence Act; and further authorizing theexecution of other necessary and convenient agreements for the receipt,tracking, transferring, management, and sale of the environmentalattributes.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117491&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117302",
    "committee": "Built Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Oct 10,2011",
    "record_type": "Council Bill ",
    "sponsor": "CLARK",
    "title": " AN ORDINANCE relating to land use and zoning, establishingprocedures for application of incentive provisions for affordable housing;amending sections 23.30.010, 23.34.008, 23.40.020, 23.45.502, 23.45.510,23.47A.002, 23.47A.013, 23.58A.002, and 23.84A.018 of the Seattle MunicipalCode; and adding new Sections 23.58A.025, 23.58A.026, and 23.58A.028.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117302&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117490",
    "committee": "Energy and Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jun 11,2012",
    "indexing_terms": "ENERGY-RESOURCES, ENERGY-FACILITIES, CONTRACTS, WIND-ENERGY",
    "record_type": "Council Bill ",
    "sponsor": " O'BRIEN",
    "title": " AN ORDINANCE relating to the City Light Department; authorizingthe execution of a confirmation agreement with Camp Reed Wind Park, LLC for thepurchase of environmental attributes, which include renewable energycertificates that are necessary or convenient for meeting the requirements ofthe Washington State Energy Independence Act; and further authorizing theexecution of other necessary and convenient agreements for the receipt,tracking, transferring, management, and sale of the environmentalattributes.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117490&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117487",
    "committee": "Public Safety, Civil Rights, and Technology",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jun 4,2012",
    "indexing_terms": "ELECTRONIC-NETWORKS, TELECOMMUNICATIONS",
    "record_type": "Council Bill ",
    "sponsor": "HARRELL",
    "title": " AN ORDINANCE relating to private party use of the City's fiberoptic cable network; authorizing the Chief Technology Officer to enteragreements allowing private parties to use the excess capacity of the City'sfiber optic cable network for providing high speed internet services and forother lawful purposes; amending Ordinance 117981 to allow agreements forprivate use; creating a fund for the financial transactions associated withprivate use; providing for an interfund loan; and amending the 2012 budget,Ordinance 123758, by adding a new budget control level and increasingappropriations; all by a three- fourths vote of the City Council.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117487&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117479",
    "committee": "Transportation",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Jul 2,2012",
    "indexing_terms": " VACATING, SEATTLE-UNIVERSITY,ALLEYS, FIRST-HILL",
    "misc_notes": " Originally referred toTransportation Committee on5/29/12.",
    "record_type": "Council Bill ",
    "sponsor": "RASMUSSEN",
    "title": " AN ORDINANCE vacating the alley in Block A, W.C. Squires Replatof Block 8, Squire Park Addition to the City of Seattle, on the petition ofSeattle University as reflected in Clerk File 305367.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117479&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117065",
    "committee": " Regional Development and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Dec 6,2010",
    "record_type": "Council Bill ",
    "sponsor": " CONLIN",
    "title": " AN ORDINANCE relating to land use and zoning; amending Section23.55.034 of the Seattle Municipal Code, allowing signs on buildings indowntown zones to be placed more than sixty five feet above ground level undercertain circumstances, and updating related sign code provisions in the Land Use Code.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117065&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117475",
    "committee": " PublicSafety, Civil Rights, and Technology",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " May 29,2012",
    "indexing_terms": " WASHINGTON-STATE, KING-COUNTY,DEPARTMENT-OF-HOMELAND-SECURITY, EMERGENCY-MANAGEMENT, GRANTS,INTERGOVERNMENTAL-RELATIONS, FIRE-DEPARTMENT, POLICE-DEPARTMENT,FINANCE",
    "record_type": "Council Bill ",
    "sponsor": " HARRELL",
    "title": " AN ORDINANCE relating to security from terrorism; authorizingthe City to partner with the State of Washington and King County to receivefinancial assistance from the Department of Homeland Security (DHS), Office forState and Local Government Coordination and Preparedness under the Urban AreasSecurity Initiative Grant for Federal Fiscal Year (FFY) 2011 (UASI FFY '11),authorizing an application for allocation of funds under that agreement,increasing appropriations to the Seattle Police Department and Seattle FireDepartment in the 2012 Budget, and ratifying and confirming prior acts; all bya three-fourths vote of the City Council.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117475&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117473",
    "committee": " Planning,Land Use, and Sustainability",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " May 21,2012",
    "indexing_terms": " MUNICIPAL-CODE, AMENDMENT,NOISE",
    "record_type": "Council Bill ",
    "sponsor": " CONLIN",
    "title": " AN ORDINANCE relating to noise control and amending Section25.08.501 of the Seattle Municipal Code.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117473&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117468",
    "committee": "Libraries, Utilities, and Center",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " May 14,2012",
    "indexing_terms": " SEATTLE-PUBLIC-UTILITIES,INTERLOCAL-AGREEMENTS, DEPARTMENT-OF-ECOLOGY, ENVIRONMENTAL-PROTECTION-AGENCY,SANITARY-SEWERS, STORM-SEWERS, KING-COUNTY, WATER-POLLUTION,ENVIRONMENTAL-PROTECTION",
    "record_type": "Council Bill ",
    "sponsor": " GODDEN",
    "title": " AN ORDINANCE relating to Seattle Public Utilities; authorizingthe Director of Seattle Public Utilities to sign and to fulfill the obligationsin a Consent Decree by the United States Environmental Protection Agency andthe Washington State Department of Ecology.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117468&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117450",
    "committee": " Economic Resiliency andRegional Relations",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Apr 23,2012",
    "indexing_terms": " HISTORIC-BUILDINGS-AND-SITES, LANDMARKS,INTERBAY",
    "record_type": "Council Bill ",
    "sponsor": " CLARK",
    "title": " AN ORDINANCE relating to historic preservation, imposingcontrols upon the Admiral's House, a landmark designated by the LandmarksPreservation Board under Chapter 25.12 of the Seattle Municipal Code, andadding it to the Table of Historical Landmarks contained in Chapter 25.32 ofthe Seattle Municipal Code.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117450&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117440",
    "committee": " Libraries, Utilities,and Center",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Apr 2,2012",
    "indexing_terms": " SOLID-WASTE, SOLID-WASTE-DISPOSAL,PUBLIC-SERVICES",
    "record_type": "Council Bill ",
    "sponsor": " CONLIN",
    "title": " AN ORDINANCE relating to the solid waste system of SeattlePublic Utilities; establishing rates and charges for solid waste services forthe Every Other Week Garbage Pilot Program; and amending Chapter 21.40.050 ofthe Seattle Municipal Code.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117440&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117286",
    "committee": "Built Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Sep 6,2011",
    "record_type": "Council Bill ",
    "sponsor": " CLARK",
    "title": " AN ORDINANCE related to land use and zoning, amending Section23.76.026 of the Seattle Municipal Code to clarify provisions related tostructure height measurement for certain types of development consistent withthe Comprehensive Plan, and ratifying and confirming certain prioracts.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117286&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117271",
    "committee": "Built Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Aug 15,2011",
    "indexing_terms": " LAND-USE-PLANNING, REZONES, ROOSEVELT",
    "misc_notes": " ThisCouncil Bill was replaced by <a href=\"http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=&s4=123816&s2=&s5=&Sect4=AND&l=20&Sect2=THESON&Sect3=PLURON&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=1&f=G\">Ordinance 123816</a>, passed by theFull Councilon January 30, 2012.",
    "record_type": "Council Bill ",
    "sponsor": " CLARK",
    "title": " AN ORDINANCE relating to land use and zoning within theRoosevelt Residential Urban Village, changing the zoning designations ofcertain lands, establishing a new Station Area Overlay District, expanding anexisting pedestrian zoning designation, modifying certain general locationalcriteria for single family zones, and amending sections: 23.34.010 and amendingthe Official Land Use Map, Chapter 23.32, at pages 43 and 60 to rezone areaswithin the Roosevelt Residential Urban Village.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117271&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117166",
    "committee": "Transportation",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " May 2,2011",
    "indexing_terms": "STREET-USE-PERMITS, FEES, STREETS, SHORELANDS",
    "record_type": "Council Bill ",
    "sponsor": " RASMUSSEN",
    "title": " AN ORDINANCE relating to Shoreline Street End permits; amendingthe current Seattle Department ofTransportation Street Use Fee Schedule byamending the Shoreline Street End permit fee methodology, and repealing Section1 and Attachment A of Ordinance 119673 Shoreline Street End Permit FeeMethodology.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117166&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 117165",
    "committee": "Built Environment",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " May 2,2011",
    "indexing_terms": " STREET-USE-PERMITS, EATING-AND-DRINKING-PLACES,STREET-VENDING",
    "record_type": "Council Bill ",
    "sponsor": " CLARK",
    "title": " AN ORDINANCE relating to street-food vending, merchandisedisplays, and sidewalk cafes; amending Sections 11.14.450, 11.16.280,11.23.420, 11.23.440, 11.31.121, 11.72.430, 15.02.042, 15.02.044, 15.02.046,15.02.048, 15.04.074, 15.16.010, 15.16.012, 15.16.020, 15.16.040, 15.16.050,15.16.060, 15.16.070, 15.16.080, 15.17.005, 15.17.050, 15.17.080, 15.17.100,15.17.150, 15.17.200, 15.91.010, and 15.91.016 of the Seattle Municipal Code;adding Sections 11.14.157, 11.14.227, 11.14.228, 11.72.195, 15.16.075,15.17.006, 15.17.007, 15.17.008, 15.17.009, 15.17.120, 15.17.130, 15.17.152,and 15.17.250; repealing Chapter 10.10, and Sections 10.03.110, 15.17.010, and15.17.020; amending the current Seattle Department ofTransportation Street Usefee schedule by adding new vending-related Street Use permit use codes andamending vending-related Street Use permit fees.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=117165&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  },
  {
    "cf_ord_res_no_": " 116758",
    "committee": "Parks and Neighborhoods",
    "date_data_retrieved": "July 13 2012 7:43 AM ",
    "date_introduced_referred_to_committee": " Dec 7,2009",
    "indexing_terms": " SEATTLE-CENTER-FACILITIES,HIGH-SCHOOL-MEMORIAL-STADIUM,",
    "record_type": "Council Bill ",
    "sponsor": " RASMUSSEN",
    "title": " AN ORDINANCE relating to the Seattle Center Department;authorizing the execution of a Memorandum of Agreement between the City andSeattle Schools regarding Memorial Stadium; establishing the terms upon whichthe City and Seattle Schools will enter into further agreements for theexchange of certain real property interests.",
    "url": "http://clerk.seattle.gov/~scripts/nph-brs.exe?s1=&s3=116758&l=20&Sect5=CBORY&Sect6=HITOFF&d=ORDF&p=1&u=%2F~public%2Fcbory.htm&r=0&f=S"
  }
];

module.exports = bills;